# Generated by Django 5.0.14 on 2026-05-20 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0010_wireguardserver_uplink_interface'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wireguardpeer',
            options={'ordering': ['-created_at'], 'verbose_name': 'WireGuard Peer', 'verbose_name_plural': 'WireGuard Peers'},
        ),
        migrations.RemoveField(
            model_name='smtpsettings',
            name='password',
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='password_encrypted',
            field=models.TextField(blank=True, default='', help_text='SMTP password (encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='from_email',
            field=models.EmailField(help_text='The email address used as the sender (e.g., no-reply@example.com)', max_length=254),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='host',
            field=models.CharField(help_text='SMTP server host (e.g., smtp.gmail.com)', max_length=100),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='port',
            field=models.IntegerField(help_text='SMTP server port (e.g., 587 for TLS, 465 for SSL)'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='username',
            field=models.CharField(help_text='SMTP authentication username (usually your email)', max_length=100),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='allowed_ip',
            field=models.GenericIPAddressField(blank=True, help_text="VPN IP for this peer. Leave blank to auto-assign from the server's subnet.", null=True),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='allowed_ips',
            field=models.CharField(blank=True, default='', help_text="Override AllowedIPs for this specific peer. Leave blank to inherit from server (split-tunnel recommended). Set to '0.0.0.0/0, ::/0' for full-tunnel.", max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='dns',
            field=models.CharField(default='8.8.8.8,8.8.4.4', help_text='DNS servers assigned to this peer (comma-separated)', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='email',
            field=models.EmailField(help_text='Email address to send the VPN configuration and QR code to', max_length=254),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Enable or disable this peer's VPN access"),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='name',
            field=models.CharField(help_text='Full name of the peer user or device', max_length=100),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS')], default='linux', help_text='Client device OS/platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='private_key_encrypted',
            field=models.TextField(blank=True, help_text="Peer's private key, encrypted at rest (auto-generated if left blank)"),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='public_key',
            field=models.CharField(blank=True, help_text="Peer's public key (auto-generated if left blank)", max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='qr_path',
            field=models.CharField(blank=True, help_text='File path to the generated QR code image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='server',
            field=models.ForeignKey(blank=True, help_text='The WireGuard server this peer connects to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peers', to='wireguard.wireguardserver'),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='server_endpoint',
            field=models.CharField(blank=True, help_text='Override the server endpoint for this peer (optional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='allowed_ips',
            field=models.CharField(blank=True, default='', help_text="AllowedIPs for peer configs. Leave blank for split-tunnel (auto-derived from server subnet — recommended). Set to '0.0.0.0/0, ::/0' for full-tunnel (routes ALL traffic through VPN).", max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='dns',
            field=models.CharField(default='8.8.8.8,8.8.4.4', help_text='DNS servers pushed to peers (comma-separated)', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='interface',
            field=models.CharField(default='wg0', help_text='WireGuard network interface name (default: wg0)', max_length=10),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this server instance'),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='mtu',
            field=models.IntegerField(default=1420, help_text='Maximum Transmission Unit size (default: 1420)'),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='name',
            field=models.CharField(help_text='Internal name for this server (e.g., Main Server)', max_length=100),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='persistent_keepalive',
            field=models.IntegerField(default=25, help_text='Keepalive interval in seconds for NAT traversal (default: 25)'),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='port',
            field=models.IntegerField(default=51820, help_text='Listen port for incoming VPN connections (default: 51820)'),
        ),
        migrations.AlterField(
            model_name='wireguardserver',
            name='uplink_interface',
            field=models.CharField(default='eth0', help_text='Public internet facing interface for NAT (default: eth0)', max_length=15),
        ),
    ]
